SUBSCRIPTIONS_NOT_FOUND_ERROR = {
    "SUBSCRIPTIONS_NOT_FOUND": "SUBSCRIPTIONS_NOT_FOUND"
    }
ADD_SUBSCRIPTION_FAILED_ERROR = {
    "DUPLICATE_CATEGORY": "DUPLICATE_CATEGORY",
    "ADD_SUBSCRIPTION_FAILED": "ADD_SUBSCRIPTION_FAILED"
}
ADD_TOPUP_FAILED_ERROR = {
    "ADD_TOPUP_FAILED": "ADD_TOPUP_FAILED",
    "DUPLICATE_TOPUP": "DUPLICATE_TOPUP"
}
INVALID_DATE_ERROR = {
    "INVALID_DATE":"INVALID_DATE"
}

# print(ADD_TOPUP_FAILED_ERROR["ADD_TOPUP_FAILED"], SUBSCRIPTIONS_NOT_FOUND_ERROR["SUBSCRIPTIONS_NOT_FOUND"], end=' ')